#  8.5-实现Promise.any

## 描述

在实现之前我们先来看一看MDN的描述：[Promise.any](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/any)， 总结

- `Promise.any()` 接收一个Promise可迭代对象，只要其中的一个 promise 成功，就返回那个已经成功的 promise 。
- 如果可迭代对象中没有一个 promise 成功（即所有的 promises 都失败/拒绝），就返回一个失败的 promise 和`AggregateError`类型的实例，它是 Error 的一个子类，用于把单一的错误集合在一起。

### 语法

```js
Promise.any(iterable);
```

### 参数

`iterable`: 一个[可迭代](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol)的对象，例如 [Array](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array)

### 返回值

- 如果传入了一个空的可迭代对象，那么就会返回一个已经被拒的 `promise`
- 如果传入了一个不含有 `promise` 的可迭代对象，那么就会返回一个异步兑现的 `promise`
- 其余情况下都会返回一个处于等待状态的 `promise`。如果可迭代对象中的任意一个 `promise` 兑现了，那么这个处于等待状态的 `promise` 就会异步地（调用栈为空时）切换至兑现状态。如果可迭代对象中的所有 `promise` 都被拒绝了，那么这个处于等待状态的 `promise` 就会异步地切换至被拒状态

## 说明

`Promise.any`方法用于获取首个兑现的 `promise` 的值。只要有一个 `promise` 兑现了，那么此方法就会提前结束，而不会继续等待其他的 `promise` 全部敲定

不像 [`Promise.all()`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) 会返回一组兑现值那样，我们只能得到一个兑现值（假设至少有一个 `promise` 兑现）。当我们只需要一个 `promise` 兑现，而不关心是哪一个兑现时此方法很有用的。

同时，也不像 [`Promise.race()`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/race) 总是返回第一个敲定值（兑现或拒绝）那样，这个方法返回的是第一个`兑现的`值。这个方法将会忽略掉所有的被拒绝的 `promise`，直到第一个 `promise` 兑现。

### [兑现（Fulfillment）](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/any#兑现（fulfillment）)

该方法所返回的 `promise` 会以可迭代对象内首个兑现的 `promise` 的兑现值来作为它自己的兑现值，或者会以可迭代对象内首个非 `promise` 值来作为它自己的兑现值，该方法不会关心其他的 `promise` 是兑现了还是被拒了。

- 如果传入的可迭代对象是非空的，那么当可迭代对象内的任意一个 `promise` 兑现后，或者当可迭代对象内存在非 `promise` 值时，该方法所返回的 `promise` 都会异步的变成兑现状态。

### [拒绝（Rejection）](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/any#拒绝（rejection）)

如果可迭代对象内所有的 `promises` 都被拒绝了，那么该方法所返回的 `promise` 就会异步的切换至被拒状态，并用一个 [`AggregateError`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/AggregateError)（继承自 [`Error`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Error)）实例来作为它的拒因。它包含一个 `errors` 属性，该属性是一个用于存储拒因的数组。

- 如果传入了一个空的可迭代数组，那么该方法就会返回一个已经被拒 `promise`，其拒因是一个 `AggregateError` 实例，该实例的 `errors` 属性会是一个空数组。

## 使用

我们可以通过使用来一步步去解析如何实现的

### 使用1： 如果传入的参数是一个空的可迭代对象，那么就会返回一个已经被拒的 `promise`。

```js
// 传入空的可迭代对象
Promise.any([]).then(res => {
  console.log(res) // AggregateError: All promises were rejected
})
// 传入非可迭代对象
Promise.any({}) // object is not iterable (cannot read property Symbol(Symbol.iterator))
```

在上面例子中, 如果传入的是非可迭代对象, 则报错, 如果传入空的可迭代对象, 那么就会返回一个已经被拒的 `promise`

### 实现1

```js
Promise.any = function (promises) {
  // 返回值必定是一个promise
  return new Promise((resolve, reject) => {
    // promises[Symbol.iterator]如果是一个函数, 就说明是可迭代对象
    if (typeof promises[Symbol.iterator] === 'function') {
      // 如果传入的参数是一个空的可迭代对象，那么就会返回一个已经被拒的 promise
      if (promises.length === 0) {
        return reject(new AggregateError([], 'All promises were rejected'))
      }
    } else {
      return reject(new TypeError(`${typeof promises} is not iterable (cannot read property Symbol(Symbol.iterator))`))
    }
  })
}
```

### 使用2:

- 传入的三个都是promise对象

  ```js
  // Promise.resolve返回的是一个promise对象
  const p1 = Promise.resolve(3) // promise1
  const p2 = Promise.resolve(6) // promise2
  const p3 = Promise.resolve('foo')
  
  Promise.any([p1, p2, p3]).then(values => {
    console.log(values) // 3
  })
  ```
  
  如果有成功的就返回第一个成功的值
  
  
  
- 传入的有一个是非promise对象

  ```js
  // Promise.resolve返回的是一个promise对象
  const p1 = Promise.resolve(3) // promise1
  const p2 = 1234 // 非promise值
  const p3 = Promise.resolve('foo')
  
  Promise.any([p1, p2, p3]).then(values => {
    console.log(values)  // 3
  })
  ```

  如果有成功的就返回第一个成功的值

  

- 传入异步的成功的

  ```js
  const pErr = new Promise((resolve, reject) => {
    reject("总是失败");
  });
  
  const pSlow = new Promise((resolve, reject) => {
    setTimeout(resolve, 500, "最终完成");
  });
  
  const pFast = new Promise((resolve, reject) => {
    setTimeout(resolve, 100, "很快完成");
  });
  
  Promise.any([pErr, pSlow, pFast]).then((value) => {
    console.log(value); // 很快完成
  })
  ```

  

- 传入失败的promise对象

  ```js
  // Promise.resolve返回的是一个promise对象
  const p1 = Promise.resolve(3) // promise1
  const p2 = 1234 // 非promise值
  const p3 = new Promise((resolve, reject) => {
    reject('error') // 失败的promise对象
  })
  
  Promise.any([p1, p2, p3]).then(values => {
    console.log(values)  // 3
  })
  ```



- 传入全是失败的promise对象

  ```js
  const p1 = new Promise((resolve, reject) => {
    reject('error1') // 失败的promise对象1
  })
  const p2 = new Promise((resolve, reject) => {
    reject('error2') // 失败的promise对象2
  })
  const p3 = new Promise((resolve, reject) => {
    reject('error3') // 失败的promise对象3
  })
  
  Promise.any([p1, p2, p3]).then(values => {
    console.log(values) // AggregateError: All promises were rejected
  })
  ```

  全部失败了, 会返回`AggregateError: All promises were rejected`

### 实现2

```js
Promise.any = function (promises) {
  // 返回值必定是一个promise
  return new Promise((resolve, reject) => {
    let errors = [] // 存储失败的结果
    let count = 0 // 计数器
    promises.forEach((item, index) => {
      // Promise.resolve方法中已经判断了参数是否为promise与thenable对象，所以无需在该方法中再次判断
      Promise.resolve(item).then(
        value => {
          // 只要其中的一个 promise 成功，就返回那个已经成功的 promise 
          resolve(value)
        },
        reason => {
          count++
          errors.push(reason)
          // 如果可迭代对象中没有一个 promise 成功，就返回一个失败的 promise 和AggregateError类型的实例
          // AggregateError是 Error 的一个子类，用于把单一的错误集合在一起
          count === promises.length && reject(new AggregateError(errors, 'All promises were rejected'))
        }
      )
    })
  })
}
```



### 整体实现

```js
Promise.any = function (promises) {
  // 返回值必定是一个promise
  return new Promise((resolve, reject) => {
    // promises[Symbol.iterator]如果是一个函数, 就说明是可迭代对象
    if (typeof promises[Symbol.iterator] === 'function') {
      // 如果传入的参数是一个空的可迭代对象，那么就会返回一个已经被拒的 promise
      if (promises.length === 0) {
        return reject(new AggregateError([], 'All promises were rejected'))
      }
      let errors = [] // 存储失败的结果
      let count = 0 // 计数器
      promises.forEach((item, index) => {
        // Promise.resolve方法中已经判断了参数是否为promise与thenable对象，所以无需在该方法中再次判断
        Promise.resolve(item).then(
          value => {
            // 只要其中的一个 promise 成功，就返回那个已经成功的 promise
            resolve(value)
          },
          reason => {
            count++
            errors.push(reason)
            // 如果可迭代对象中没有一个 promise 成功，就返回一个失败的 promise 和AggregateError类型的实例
            // AggregateError是 Error 的一个子类，用于把单一的错误集合在一起
            count === promises.length && reject(new AggregateError(errors, 'All promises were rejected'))
          }
        )
      })
    } else {
      return reject(new TypeError(`${typeof promises} is not iterable (cannot read property Symbol(Symbol.iterator))`))
    }
  })
}

```



## 总结

- `Promise.any`在本质上，这个方法和`Promise.all()`是相反的
- 只要其中的一个 promise 成功，就返回那个已经成功的 promise
- 或者等待全部失败, 返回一个失败的 promise 和AggregateError类型的实例